### ISSUE TITLE
Webhook problems

### ISSUE THREAD

**Issue by qualityplatforms** [picqer/exact-php-client#140]
Hi all,

When creating an webhook subscription i can't get it working. I just was wondering for an working webhook example. 

```PHP
<?php

// Autoload composer installed libraries
require __DIR__ . '/../vendor/autoload.php';

/**
 * Function to retrieve persisted data for the example
 * @param string $key
 * @return null|string
 */
function getValue($key)
{
    $storage = json_decode(file_get_contents('storage.json'), true);
    if (array_key_exists($key, $storage)) {
        return $storage[$key];
    }
    return null;
}

/**
 * Function to persist some data for the example
 * @param string $key
 * @param string $value
 */
function setValue($key, $value)
{
    $storage       = json_decode(file_get_contents('storage.json'), true);
    $storage[$key] = $value;
    file_put_contents('storage.json', json_encode($storage));
}

/**
 * Function to authorize with Exact, this redirects to Exact login promt and retrieves authorization code
 * to set up requests for oAuth tokens
 */
function authorize()
{
    $connection = new \Picqer\Financials\Exact\Connection();
    $connection->setRedirectUrl('https://domain/exact/example/example.php');
    $connection->setExactClientId('');
    $connection->setExactClientSecret('');
    $connection->redirectForAuthorization();
}

/**
 * Callback function that sets values that expire and are refreshed by Connection.
 *
 * @param \Picqer\Financials\Exact\Connection $connection
 */
function tokenUpdateCallback(\Picqer\Financials\Exact\Connection $connection) {
    // Save the new tokens for next connections
    setValue('accesstoken', $connection->getAccessToken());
    setValue('refreshtoken', $connection->getRefreshToken());

    // Save expires time for next connections
    setValue('expires_in', $connection->getTokenExpires());
}

/**
 * Function to connect to Exact, this creates the client and automatically retrieves oAuth tokens if needed
 *
 * @return \Picqer\Financials\Exact\Connection
 * @throws Exception
 */
function connect()
{
    $connection = new \Picqer\Financials\Exact\Connection();
    $connection->setRedirectUrl('https://domain/exact/example/example.php');
    $connection->setExactClientId('');
    $connection->setExactClientSecret('');

    // Retrieves authorizationcode from database
    if (getValue('authorizationcode')) {
        $connection->setAuthorizationCode(getValue('authorizationcode'));
    }

    // Retrieves accesstoken from database
    if (getValue('accesstoken')) {
        $connection->setAccessToken(getValue('accesstoken'));
    }

    // Retrieves refreshtoken from database
    if (getValue('refreshtoken')) {
        $connection->setRefreshToken(getValue('refreshtoken'));
    }

    // Retrieves expires timestamp from database
    if (getValue('expires_in')) {
        $connection->setTokenExpires(getValue('expires_in'));
    }

    // Set callback to save newly generated tokens
    $connection->setTokenUpdateCallback('tokenUpdateCallback');

    // Make the client connect and exchange tokens
    try {
        $connection->connect();
    } catch (\Exception $e) {
        throw new Exception('Could not connect to Exact: ' . $e->getMessage());
    }

    return $connection;
}

// If authorization code is returned from Exact, save this to use for token request
if (isset($_GET['code']) && is_null(getValue('authorizationcode'))) {
    setValue('authorizationcode', $_GET['code']);
}

// If we do not have a authorization code, authorize first to setup tokens
if (getValue('authorizationcode') === null) {
    authorize();
}


function handle(Authentication $exactAuth)
{
    // First remove all existing subscriptions
    $this->deleteSubscriptions($exactAuth);

    foreach ($this->topics as $topic) {
        $subscription = new WebhookSubscription($exactAuth->getConnection());
        $subscription->CallbackURL = $this->callbackUrl;
        $subscription->Topic = $topic;
        $subscription->save();
    }
}

// Create the Exact client
$connection = connect();

// Get the journals from our administration
try {

    echo handle(authorize());

} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}
```

This is what i have at this moment. It just won't work.

Can anyone help me?

**Comment by tomcoonen** [comment]
@qualityplatforms This actually works:
```
$subscription = new WebhookSubscription($exactAuth->getConnection());
$subscription->CallbackURL = $this->callbackUrl;
$subscription->Topic = $topic;
$subscription->save();
```

If you don't get this working, please be more detailed in your problem description, what errors do occur?

**Comment by qualityplatforms** [comment]
Well, there are many:

1. What is $exactAuth->getConnection()?
```
Searching 61 files for "getConnection"

0 matches
```

2. Thanks for the P.S.

3. Well, i can't use postman (oauth2 error) and got many 400 errors inside my error log.

**Comment by tomcoonen** [comment]
Try to make a connection with Exact first, that seems to be failing for you in the first place.
I don't know where this code comes from, but it doesn't work since `authorize()` doesn't return anything and you are trying to `handle(authorize())`.

**Comment by qualityplatforms** [comment]
This code is from example/example.php. If i try to use the following code, it also won't work.

```
	require __DIR__ . '/../vendor/autoload.php';

	$connection = new \Picqer\Financials\Exact\Connection();
	$connection->setRedirectUrl('https://qp1.nl/exact/example/example.php');
	$connection->setExactClientId('The client id');
	$connection->setExactClientSecret('the client secret');

	$callback = 'https://domain/exact/example/exactwebhook.php';
	$topic = 'Contacts';

	$subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection->getConnection());
	$subscription->CallbackURL = $callback;
	$subscription->Topic = $topic;
	$subscription->save();
```

The error i got: Call to undefined method Picqer\\Financials\\Exact\\Connection::getConnection()

**Comment by stephangroen** [comment]
```php
	$subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection->getConnection());
```

should be

```php
	$subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection);
```

You inject the `Connection` object into `WebhookSubscription`.

**Comment by qualityplatforms** [comment]
Thank you Stephan. I still get the following errors:

```
Fatal error: Uncaught exception 'Picqer\Financials\Exact\ApiException' with message 'Error 400: Bad Request' in /exact/src/Picqer/Financials/Exact/Connection.php:557 

Stack trace: 
	#0 /exact/src/Picqer/Financials/Exact/Connection.php(197): Picqer\Financials\Exact\Connection->parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException)) 
	#1 /home/qdp/domains/qp1.nl/public_html/exact/src/Picqer/Financials/Exact/Me.php(79): Picqer\Financials\Exact\Connection->get('current/Me') 
	#2 /home/qdp/domains/qp1.nl/public_html/exact/src/Picqer/Financials/Exact/Connection.php(386): Picqer\Financials\Exact\Me->find() 
	#3 /home/qdp/domains/qp1.nl/public_html/exact/src/Picqer/Financials/Exact/Connection.php(498): Picqer\Financials\Exact\Connection->getCurrentDivisionNumber() 
	#4 /home/qdp/domains/qp1.nl/public_html/exact/src/Picqer/Financials/Exact/Connection.php(209): Picqer\Financials\Exact\Connection->formatUrl('webhooks/Webhoo...') 
	#5 /home/qdp/domains/qp in /home/qdp/domains/qp1.nl/public_html/exact/src/Picqer/Financials/Exact/Connection.php on line 557 
```

**Comment by qualityplatforms** [comment]
I still stuck at this problem. I tried to subscribe it and this also will be shown inside Exact. The only strange thing is that exact won't access when making an change so i still can't use it.

This code i use right now:

```
<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);

	require __DIR__ . '/../vendor/autoload.php';

	$connection = new \Picqer\Financials\Exact\Connection();
	$connection->setRedirectUrl('https://domain/exact/example/example.php');
	$connection->setExactClientId('the client id');
	$connection->setExactClientSecret('the client secret');

	if(!isset($_GET['code']))
	{
		$connection->redirectForAuthorization();
	}
	else
	{
		$connection->setAuthorizationCode($_GET['code']);
		$connection->setAccessToken($connection->getAccessToken());
		$connection->setRefreshToken($connection->getRefreshToken());
		$connection->setTokenExpires($connection->getTokenExpires());
		$connection->setTokenUpdateCallback('tokenUpdateCallback');

		$callback = 'https://domain/exact/example/exactwebhook.php';

		$topics = [
			'FinancialTransactions',
			'SalesOrders',
			'SalesInvoices',
			'PurchaseOrders',
			'GoodsDeliveries',
			'CostTransactions',
			'TimeTransactions',
			'Documents',
			'Quotations',
			'BankAccounts'
		];

		foreach($topics as $topic)
		{
			$subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection);
			//$subscription->deleteSubscriptions();
			$subscription->CallbackURL = $callback;
			$subscription->Topic = $topic;
			$subscription->save();
		}		
	}
```

**Comment by stephangroen** [comment]
If the webhook is correctly registered at Exact, you should be able to receive it. If you do not receive anything at the given endpoint, you should contact Exact.

**Comment by mahamood** [comment]
I am using PHP SDK (https://github.com/picqer/exact-php-client).

I subscribed using below request:
    $subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection);
   $subscription->deleteSubscriptions();
   $subscription->CallbackURL = $callback;
   $subscription->Topic = "Documents";
   $subscription->save();
Webhook Registered and Notifications are coming to webhook CallbackURL with empty response. 

Please give me suggestion how to authenticate Webhook response.
