### ISSUE TITLE
Error 400 invalid request

### ISSUE THREAD

**Issue by jasperf** [picqer/exact-php-client#553]
Post mollie payment (recurring that succeeded) we got this error using Picquer Exact bookkeeping package:

```php
Picqer\Financials\Exact\ApiException ·App\Jobs\Exact\SyncOrderJob
Error 400: {"error":"invalid_request"}
Mar 22nd 03:52:00  utc
P	|	
app/Jobs/Exact/SyncOrderJob.php:48 · App\Jobs\Exact\SyncOrderJob::handle
Release stage	production
Unhandled	true
Severity	error
App version	1.16.5
```

Any recommendations on understanding and debugging this error?

**Comment by jasperf** [comment]
New client id and new client secret added and we shall test again. Seems `.env` had not been updated with latest client id and secret. But still wonder if we could get better feedback than just an error 400 from Exact here. Rather vague `invalid request`

**Comment by remkobrenters** [comment]
All I can conclude is that the request is invalid. Can you post your request?

**Comment by jasperf** [comment]
Request failed again. Perhaps an issue with user ID.. looking into this some more.

Job:

```
attempts
2
connection
redis
name
Illuminate\Queue\CallQueuedHandler@call
queue
default
resolved
App\Jobs\Exact\SyncOrderJob
```

Error
```
Picqer\Financials\Exact\ApiExceptionApp\Jobs\Exact\SyncOrderJob
Error 400: {"error":"invalid_request"}
Linked event: 1 minute ago · Mar 24th, 08:40:05 GMT+7
```

`app/Jobs/Exact/SyncOrderJob.php:48 App\Jobs\Exact\SyncOrderJob::handle`:

```php
// Sync account
$account = new \Picqer\Financials\Exact\Account($connection);
$account->ID = data_get($account->filter("Email eq '{$this->order->email_address}'"), '0.ID', null);
$account->City = $this->order->city;
$account->Country = $this->order->country;
$account->IsSales = 'true';
```

```
ERROR Error Occurred
--
101ms before |   | PROCESS Query executed sql select * from `orders` where `orders`.`id` = ? limit 1 time 9.26ms connection mysql
```

**Comment by remkobrenters** [comment]
Most of the provided information is not relevant. When I look at the only two lines that related to the issue I do not see something that looks like it could be the issue although I don't know what data your `order->email_address` contains but assuming it is not a null this seems valid. I advise you to debug your code on a couple of places. Maybe do some tests without filtering (to see if your connection itself is working and valid), than with a hard-coded  string to search for (to exclude issues with the property in the `order` object) etc.

**Comment by jasperf** [comment]
Discussing things with Exact as well and senior developer to get more details. Did find this in logs, but need HTTP request and response as well.

```
#0 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(287): Picqer\\Financials\\Exact\\Connection->parseExceptionForErrorMessages()
#1 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Me.php(92): Picqer\\Financials\\Exact\\Connection->get()
#2 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(547): Picqer\\Financials\\Exact\\Me->find()
#3 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(681): Picqer\\Financials\\Exact\\Connection->getCurrentDivisionNumber()
#4 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(279): Picqer\\Financials\\Exact\\Connection->formatUrl()
#5 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php(111): Picqer\\Financials\\Exact\\Connection->get()
[previous exception] [object] (Picqer\\Financials\\Exact\\ApiException(code: 400): Error 400: {\"error\":\"invalid_request\"} at /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php:771)
#0 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(623): Picqer\\Financials\\Exact\\Connection->parseExceptionForErrorMessages()
#1 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(224): Picqer\\Financials\\Exact\\Connection->acquireAccessToken()
#2 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(248): Picqer\\Financials\\Exact\\Connection->checkOrAcquireAccessToken()
#3 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(282): Picqer\\Financials\\Exact\\Connection->createRequest()
#4 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Me.php(92): Picqer\\Financials\\Exact\\Connection->get()
#5 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(547): Picqer\\Financials\\Exact\\Me->find()
#6 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(681): Picqer\\Financials\\Exact\\Connection->getCurrentDivisionNumber()
#7 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(279): Picqer\\Financials\\Exact\\Connection->formatUrl()
#8 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php(111): Picqer\\Financials\\Exact\\Connection->get()
[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response:
#11 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(606): GuzzleHttp\\Client->post()
#12 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(224): Picqer\\Financials\\Exact\\Connection->acquireAccessToken()
#13 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(248): Picqer\\Financials\\Exact\\Connection->checkOrAcquireAccessToken()
#14 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(282): Picqer\\Financials\\Exact\\Connection->createRequest()
#15 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Me.php(92): Picqer\\Financials\\Exact\\Connection->get()
#16 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(547): Picqer\\Financials\\Exact\\Me->find()
#17 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(681): Picqer\\Financials\\Exact\\Connection->getCurrentDivisionNumber()
#18 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(279): Picqer\\Financials\\Exact\\Connection->formatUrl()
#19 /home/forge/site.com/releases/41/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php(11
```

**Comment by remkobrenters** [comment]
This line has my interest `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` I would say you somehow send incorrect data to the token endpoint. I would dig into this and debug what you are sending and doing there.

**Comment by remkobrenters** [comment]
Did you figure out the issue and was it something worth sharing for other developers?

**Comment by jasperf** [comment]
Trying to rerun the job post adding better error catching to connection so we did

```
dep ssh prod
forge@app-prod-w-2:~/domain.com/current$ php artisan tinker
Psy Shell v0.11.1 (PHP 8.0.12 — cli) by Justin Hileman
>>> \App\Jobs\Exact\SyncOrderJob::dispatch(\App\Order::find(45));
=> Illuminate\Foundation\Bus\PendingDispatch {#3852}
>>>
```

but that does not seem to work. Seeing nothing in Horizon and not getting errors registered. So not not quite done..

**Comment by jasperf** [comment]
More detailed error report on test

```
Picqer\Financials\Exact\ApiExceptionApp\Jobs\Exact\SyncOrderJob
Error 400: {"error":"invalid_request"}
2 minutes ago
Apr 13th, 17:16:13 GMT+7
production
unhandled
Picqer\Financials\Exact\ApiException · Error 400: {"error":"invalid_request"}
app/Jobs/Exact/SyncOrderJob.php:50 App\Jobs\Exact\SyncOrderJob::handle
            // Sync account
            $account = new \Picqer\Financials\Exact\Account($connection);
            $account->ID = data_get($account->filter("Email eq '{$this->order->email_address}'"), '0.ID', null);
            $account->City = $this->order->city;
            $account->Country = $this->order->country;
            $account->IsSales = 'true';
Caused By: Picqer\Financials\Exact\ApiException · Error 400: {"error":"invalid_request"}
app/Jobs/Exact/SyncOrderJob.php:50 App\Jobs\Exact\SyncOrderJob::handle
Caused By: GuzzleHttp\Exception\ClientException · Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_request"}
app/Jobs/Exact/SyncOrderJob.php:50 App\Jobs\Exact\SyncOrderJob::handle
```

**Comment by remkobrenters** [comment]
None of the provided code explains how you configure your connection credentials which result in the 400 error with the token request.
